// Preencha estes valores para ativar Supabase Auth e a tabela public.students.
const SUPABASE_URL = 'https://ynvecjvjstukibbxauya.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_XOe920eAOAbp1PpuuzVnGg_dfiiAJZ-';
const supabaseClient = SUPABASE_URL && SUPABASE_ANON_KEY ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const STORAGE_KEY = 'teste-pratico-students';
let students = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null') || [
	{ id: '1', date: '2026-09-03', name: 'Mariana Costa', reason: 'TESTE', result: 'APROVADO' }, { id: '2', date: '2026-09-04', name: 'Rafael Mendes', reason: 'TESTE', result: 'REPROVADO' }, { id: '3', date: '2026-09-05', name: 'Beatriz Lima', reason: 'RETESTE', result: 'APROVADO' }, { id: '4', date: '2026-09-06', name: 'Lucas Andrade', reason: 'TESTE', result: 'PENDENTE' }, { id: '5', date: '2026-09-09', name: 'Camila Rocha', reason: 'RETESTE', result: 'APROVADO' }
];
let editingId = null; let sortKey = 'date'; let sortDirection = -1; let currentView = 'records';
const $ = id => document.getElementById(id);
const esc = value => String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const formatDate = date => new Intl.DateTimeFormat('pt-BR', { timeZone: 'America/Sao_Paulo', day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${date}T12:00:00`)).replace('.', '');
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Sao_Paulo' }).format(new Date());
const save = () => localStorage.setItem(STORAGE_KEY, JSON.stringify(students));
const toast = message => { $('toast').textContent = message; $('toast').classList.remove('hidden'); setTimeout(() => $('toast').classList.add('hidden'), 2600); };
const badge = value => { const map = { TESTE: ['Teste', 'test'], RETESTE: ['Reteste', 'retest'], APROVADO: ['Aprovado', 'approved'], REPROVADO: ['Reprovado', 'failed'], PENDENTE: ['Pendente', 'pending'] }; return `<span class="pill ${map[value][1]}">${map[value][0]}</span>`; };
function renderRecords() {
	const query = $('searchInput').value.toLowerCase(); const reason = $('reasonFilter').value; const result = $('resultFilter').value;
	const rows = students.filter(item => item.name.toLowerCase().includes(query) && (!reason || item.reason === reason) && (!result || item.result === result)).sort((a, b) => { const av = a[sortKey], bv = b[sortKey]; return String(av).localeCompare(String(bv), 'pt-BR') * sortDirection; });
	$('recordsBody').innerHTML = rows.length ? rows.map(item => `<tr><td class="date-cell">${formatDate(item.date)}</td><td class="name-cell">${esc(item.name)}</td><td>${badge(item.reason)}</td><td>${badge(item.result)}</td><td style="text-align:right; display:flex; justify-content:flex-end; gap:8px;"><button class="icon-btn edit-btn" data-id="${item.id}" title="Editar cadastro"><i data-lucide="pencil" width="16"></i></button><button class="icon-btn delete-btn" data-id="${item.id}" title="Excluir cadastro"><i data-lucide="trash-2" width="16"></i></button></td></tr>`).join('') : `<tr><td colspan="5"><div class="empty"><i data-lucide="inbox" width="28"></i><div>Nenhum cadastro encontrado</div></div></td></tr>`;
	$('quickStats').innerHTML = `<div class="stat-card"><span class="stat-label">Total cadastrados</span><strong>${students.length}</strong><small>alunos no período</small></div><div class="stat-card"><span class="stat-label">Testes</span><strong>${students.filter(x => x.reason === 'TESTE').length}</strong><small>primeira avaliação</small></div><div class="stat-card"><span class="stat-label">Retestes</span><strong>${students.filter(x => x.reason === 'RETESTE').length}</strong><small>nova tentativa</small></div><div class="stat-card"><span class="stat-label">Aprovação geral</span><strong>${percent(students.filter(x => x.result === 'APROVADO').length, students.filter(x => x.result !== 'PENDENTE').length)}%</strong><small>dos avaliados</small></div>`;
	lucide.createIcons(); document.querySelectorAll('.edit-btn').forEach(button => button.onclick = () => openModal(button.dataset.id)); document.querySelectorAll('.delete-btn').forEach(button => button.onclick = () => deleteStudent(button.dataset.id));
}
const percent = (value, total) => total ? Math.round(value / total * 100) : 0;
function renderStats() {
	const year = $('yearFilter').value; const month = $('monthFilter').value; const filtered = students.filter(item => (!year || item.date.startsWith(year)) && (!month || item.date.slice(5, 7) === month)); const evaluated = filtered.filter(x => x.result !== 'PENDENTE'); const approved = evaluated.filter(x => x.result === 'APROVADO'); const rejected = evaluated.filter(x => x.result === 'REPROVADO'); const tests = filtered.filter(x => x.reason === 'TESTE'); const testApproved = tests.filter(x => x.result === 'APROVADO'); const testRejected = tests.filter(x => x.result === 'REPROVADO');
	const monthNames = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']; const chart = monthNames.map((label, index) => { const monthKey = String(index + 1).padStart(2, '0'); const approvedMonth = filtered.filter(x => (year ? x.date.startsWith(`${year}-${monthKey}`) : x.date.slice(5, 7) === monthKey) && x.result === 'APROVADO').length; const rejectedMonth = filtered.filter(x => (year ? x.date.startsWith(`${year}-${monthKey}`) : x.date.slice(5, 7) === monthKey) && x.result === 'REPROVADO').length; return `<div class="bar-group"><div class="bar" style="height:${Math.max(approvedMonth * 25, approvedMonth ? 5 : 2)}px" title="${approvedMonth} aprovados"></div><div class="bar rejected" style="height:${Math.max(rejectedMonth * 25, rejectedMonth ? 5 : 2)}px" title="${rejectedMonth} reprovados"></div><span class="bar-label">${label}</span></div>`; }).join('');
	$('statsGrid').innerHTML = `<div class="chart-card"><div class="card-title"><div><h3>Resultado por mês</h3><p>Comparativo de aprovados e reprovados</p></div></div><div class="bar-chart">${chart}</div><div class="legend"><span>Aprovados</span><span class="reject">Reprovados</span></div></div><div class="metrics-card"><div class="card-title"><div><h3>Resumo do período</h3><p>${filtered.length} registros encontrados</p></div></div>${metric('Total de alunos', filtered.length, 100, '')} ${metric('Testes realizados', tests.length, percent(tests.length, filtered.length), 'yellow')} ${metric('Aprovados', approved.length, percent(approved.length, evaluated.length), '')} ${metric('Reprovados', rejected.length, percent(rejected.length, evaluated.length), 'red')} ${metric('Teste + aprovado', testApproved.length, percent(testApproved.length, tests.filter(x => x.result !== 'PENDENTE').length), '')} ${metric('Teste + reprovado', testRejected.length, percent(testRejected.length, tests.filter(x => x.result !== 'PENDENTE').length), 'red')}</div>`;
}
const metric = (label, value, progress, color) => `<div class="metric-row"><div class="metric-top"><strong>${label}</strong><span>${value} <small>(${progress}%)</small></span></div><div class="progress"><i class="${color}" style="width:${progress}%"></i></div></div>`;
function openModal(id = null) { editingId = id; const item = students.find(x => x.id === id); $('modalTitle').textContent = id ? 'Editar cadastro' : 'Novo cadastro'; $('studentDate').value = item?.date || today(); $('studentName').value = item?.name || ''; $('studentReason').value = item?.reason || 'TESTE'; $('studentResult').value = item?.result || 'PENDENTE'; $('modalBackdrop').classList.remove('hidden'); setTimeout(() => $('studentName').focus(), 50); }
function closeModal() { $('modalBackdrop').classList.add('hidden'); }
function setView(view) { currentView = view; $('recordsView').classList.toggle('hidden', view !== 'records'); $('statsView').classList.toggle('hidden', view !== 'stats'); $('topTitle').textContent = view === 'records' ? 'Alunos' : 'Estatísticas'; document.querySelectorAll('.nav button').forEach(btn => btn.classList.toggle('active', btn.dataset.view === view)); if (view === 'stats') renderStats(); $('sidebar').classList.remove('open'); }
function populateYearFilter() { const years = [...new Set([new Date().getFullYear(), ...students.map(x => Number(x.date.slice(0, 4)))])].sort((a, b) => b - a); const selectedYear = $('yearFilter').value; $('yearFilter').innerHTML = '<option value="">Todos os anos</option>' + years.map(year => `<option value="${year}">${year}</option>`).join(''); $('yearFilter').value = years.includes(Number(selectedYear)) ? selectedYear : ''; }
async function loadRemoteStudents() { if (!supabaseClient) return; const { data, error } = await supabaseClient.from('students').select('id,date,name,reason,result').order('date', { ascending: false }); if (error) { toast('Não foi possível carregar os cadastros'); return; } students = data || []; populateYearFilter(); save(); }
async function saveRemoteStudent(data) { if (!supabaseClient) return; const { error } = await supabaseClient.from('students').upsert(data); if (error) toast('Salvo localmente; verifique a tabela students no Supabase'); }
async function deleteStudent(id) {
	const student = students.find(item => item.id === id);
	if (!student) return;
	const confirmed = window.confirm(`Deseja excluir o cadastro de ${student.name}?`);
	if (!confirmed) return;
	students = students.filter(item => item.id !== id);
	save();
	if (supabaseClient) {
		const { error } = await supabaseClient.from('students').delete().eq('id', id);
		if (error) toast('Cadastro removido localmente; verifique a tabela students no Supabase');
	}
	renderRecords();
	if (currentView === 'stats') renderStats();
	toast('Cadastro excluído com sucesso');
}
$('loginForm').onsubmit = async event => { event.preventDefault(); const email = $('loginEmail').value; const password = $('loginPassword').value; let valid = email === 'admin@teste.com' && password === 'teste123'; if (supabaseClient) { const { error } = await supabaseClient.auth.signInWithPassword({ email, password }); valid = !error; if (error) toast('E-mail ou senha inválidos'); if (valid) await loadRemoteStudents(); } if (valid) { $('loginView').classList.add('hidden'); $('appView').classList.remove('hidden'); renderRecords(); toast('Login realizado com sucesso'); } else if (!supabaseClient) toast('E-mail ou senha inválidos'); };
$('logoutBtn').onclick = () => { $('appView').classList.add('hidden'); $('loginView').classList.remove('hidden'); };
$('newBtn').onclick = () => openModal(); $('closeModal').onclick = closeModal; $('cancelModal').onclick = closeModal; $('modalBackdrop').onclick = e => { if (e.target === $('modalBackdrop')) closeModal(); };
$('studentForm').onsubmit = async e => { e.preventDefault(); const data = { date: $('studentDate').value, name: $('studentName').value.trim(), reason: $('studentReason').value, result: $('studentResult').value }; if (editingId) { data.id = editingId; students = students.map(x => x.id === editingId ? { ...x, ...data } : x); } else { data.id = crypto.randomUUID(); students.push(data); } save(); await saveRemoteStudent(data); closeModal(); renderRecords(); if (currentView === 'stats') renderStats(); toast(editingId ? 'Cadastro atualizado' : 'Cadastro salvo com sucesso'); };
document.querySelectorAll('[data-sort]').forEach(button => button.onclick = () => { const key = button.dataset.sort; sortDirection = sortKey === key ? sortDirection * -1 : -1; sortKey = key; renderRecords(); });['searchInput', 'reasonFilter', 'resultFilter'].forEach(id => $(id).oninput = renderRecords); document.querySelectorAll('.nav button').forEach(btn => btn.onclick = () => setView(btn.dataset.view)); $('menuBtn').onclick = () => $('sidebar').classList.toggle('open'); $('yearFilter').onchange = renderStats; $('monthFilter').onchange = renderStats;
populateYearFilter(); $('todayLabel').textContent = new Intl.DateTimeFormat('pt-BR', { timeZone: 'America/Sao_Paulo', day: '2-digit', month: 'long', year: 'numeric' }).format(new Date()); lucide.createIcons();
